"""Add normalized_hash

Revision ID: 5324dbbff307
Revises: b130d9646b7e
Create Date: 2026-06-25 17:39:24.649573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5324dbbff307'
down_revision: Union[str, Sequence[str], None] = 'b130d9646b7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('normalized_hash', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_knowledge_documents_normalized_hash'), ['normalized_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_documents_normalized_hash'))
        batch_op.drop_column('normalized_hash')

    # ### end Alembic commands ###
