"""add fields to knowledge_card

Revision ID: 63ea95391869
Revises: 9202a29db1bb
Create Date: 2026-08-11 20:38:45.277972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63ea95391869'
down_revision: Union[str, Sequence[str], None] = '9202a29db1bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('after_state', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('source_visual_refs', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('source_type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('source_priority', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_cards', schema=None) as batch_op:
        batch_op.drop_column('source_priority')
        batch_op.drop_column('source_type')
        batch_op.drop_column('source_visual_refs')
        batch_op.drop_column('after_state')

    # ### end Alembic commands ###
