"""Update unique constraints

Revision ID: 6cc45f907f05
Revises: 5324dbbff307
Create Date: 2026-06-25 17:50:04.843365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cc45f907f05'
down_revision: Union[str, Sequence[str], None] = '5324dbbff307'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_chunks', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_org_source_chunk', ['organization_id', 'source_id', 'chunk_index'])

    with op.batch_alter_table('knowledge_sources', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_org_source_id'), type_='unique')
        batch_op.create_unique_constraint('uq_org_series_version', ['organization_id', 'source_series_id', 'version'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_sources', schema=None) as batch_op:
        batch_op.drop_constraint('uq_org_series_version', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_org_source_id'), ['organization_id', 'id'])

    with op.batch_alter_table('knowledge_chunks', schema=None) as batch_op:
        batch_op.drop_constraint('uq_org_source_chunk', type_='unique')

    # ### end Alembic commands ###
