"""add knowledge_cards table

Revision ID: 9202a29db1bb
Revises: fdb5b5cd8720
Create Date: 2026-08-11 20:29:09.136094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9202a29db1bb'
down_revision: Union[str, Sequence[str], None] = 'fdb5b5cd8720'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_cards',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('rule_name', sa.String(length=255), nullable=False),
    sa.Column('principle', sa.Text(), nullable=False),
    sa.Column('problem_pattern', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('applicable_document_types', sa.JSON(), nullable=True),
    sa.Column('exceptions', sa.Text(), nullable=True),
    sa.Column('source_document', sa.String(length=255), nullable=False),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('source_chunk_ids', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('rights_status', sa.String(length=50), nullable=False),
    sa.Column('revision_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_cards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_cards_organization_id'), ['organization_id'], unique=False)

    op.create_table('rag_audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('question_hash', sa.String(length=64), nullable=True),
    sa.Column('answer_hash', sa.String(length=64), nullable=True),
    sa.Column('model_id', sa.String(length=255), nullable=True),
    sa.Column('model_digest', sa.String(length=255), nullable=True),
    sa.Column('embedding_model_id', sa.String(length=36), nullable=True),
    sa.Column('prompt_version', sa.String(length=50), nullable=True),
    sa.Column('prompt_hash', sa.String(length=64), nullable=True),
    sa.Column('retrieval_config', sa.JSON(), nullable=True),
    sa.Column('selected_chunk_ids', sa.JSON(), nullable=True),
    sa.Column('citation_ids', sa.JSON(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rag_audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rag_audit_logs_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rag_audit_logs_request_id'), ['request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rag_audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rag_audit_logs_request_id'))
        batch_op.drop_index(batch_op.f('ix_rag_audit_logs_organization_id'))

    op.drop_table('rag_audit_logs')
    with op.batch_alter_table('knowledge_cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_cards_organization_id'))

    op.drop_table('knowledge_cards')
    # ### end Alembic commands ###
