"""Add FAISS tables

Revision ID: ad7a4c76e4c8
Revises: 6cc45f907f05
Create Date: 2026-06-25 19:09:58.773569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad7a4c76e4c8'
down_revision: Union[str, Sequence[str], None] = '6cc45f907f05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faiss_index_metadata',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('embedding_model_id', sa.String(length=36), nullable=False),
    sa.Column('index_version', sa.Integer(), nullable=False),
    sa.Column('index_checksum', sa.String(length=64), nullable=True),
    sa.Column('vector_count', sa.Integer(), nullable=False),
    sa.Column('built_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('build_status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['embedding_model_id'], ['embedding_models.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('organization_id', 'embedding_model_id')
    )
    op.create_table('chunk_faiss_mappings',
    sa.Column('faiss_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chunk_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['knowledge_chunks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('faiss_id'),
    sa.UniqueConstraint('chunk_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chunk_faiss_mappings')
    op.drop_table('faiss_index_metadata')
    # ### end Alembic commands ###
